### ISSUE TITLE
Error setting a threshold

### ISSUE THREAD

**Issue by Alfonsso786** [YoCodingMonster/MSI-Dragon-Center-for-Linux-OpenFreezeCenter#11]
I recive this error when i set a threshold in my laptop
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.9/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "/home/alfonsojph/Documentos/Gitclones/MSI-Dragon-Center-for-Linux-main/GUI-MSI-DC-L.py", line 282, in batt_thresh
    value = entry1.get()
TypeError: get() missing 1 required positional argument: 'index1'

Currently on Manjaro KDE and I'm using an MSI Bravo 15

**Comment by YoCodingMonster** [comment]
Battery threashold is work under progress for some models
